defaults:
  - _self_

resize: 84
num_envs: 1
eval_times: 10

max_steps: 5005000
buffer_size: 100000
learning_rate: 1e-4
learning_starts: 5000
batch_size: 32
gamma: 0.99
tau: 1
target_network_freq: 1000
train_freq: 4

n_atoms: 51
v_max: 10
v_min: -10
data_efficient: False
noisy_std: 0.1
log_softmax: False

n_steps: 3
alpha: 0.6

algo_name: rainbow